package injector

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// Injector formats secrets for a specific output target.
type Injector interface {
	Inject(secrets map[string]string) (string, error)
}

// Get returns an injector by format name.
func Get(format string) (Injector, error) {
	switch format {
	case "shell", "sh", "bash", "zsh":
		return &shellInjector{}, nil
	case "dotenv", "env":
		return &dotenvInjector{}, nil
	case "jupyter", "notebook", "python":
		return &jupyterInjector{}, nil
	default:
		return nil, fmt.Errorf("unknown format %q — supported: shell, dotenv, jupyter", format)
	}
}

// WriteToFile writes injector output to a file.
func WriteToFile(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		return fmt.Errorf("could not write to %s: %w", path, err)
	}
	fmt.Fprintf(os.Stderr, "✓ Written to %s\n", path)
	return nil
}

// sortedKeys returns map keys in sorted order for deterministic output.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// --- Shell injector ---

type shellInjector struct{}

func (s *shellInjector) Inject(secrets map[string]string) (string, error) {
	var b strings.Builder
	for _, k := range sortedKeys(secrets) {
		// Escape single quotes in values
		escaped := strings.ReplaceAll(secrets[k], "'", "'\\''")
		fmt.Fprintf(&b, "export %s='%s'\n", k, escaped)
	}
	return b.String(), nil
}

// --- Dotenv injector ---

type dotenvInjector struct{}

func (d *dotenvInjector) Inject(secrets map[string]string) (string, error) {
	var b strings.Builder
	b.WriteString("# Generated by aikeys — do not commit this file\n")
	for _, k := range sortedKeys(secrets) {
		// Dotenv format: quote values that contain spaces or special chars
		v := secrets[k]
		if strings.ContainsAny(v, " \t\n#=") {
			v = `"` + strings.ReplaceAll(v, `"`, `\"`) + `"`
		}
		fmt.Fprintf(&b, "%s=%s\n", k, v)
	}
	return b.String(), nil
}

// --- Jupyter injector ---

type jupyterInjector struct{}

func (j *jupyterInjector) Inject(secrets map[string]string) (string, error) {
	var b strings.Builder
	b.WriteString("import os\n\n")
	for _, k := range sortedKeys(secrets) {
		// Escape backslashes and single quotes for Python string
		escaped := strings.ReplaceAll(secrets[k], `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, "'", "\\'")
		fmt.Fprintf(&b, "os.environ['%s'] = '%s'\n", k, escaped)
	}
	return b.String(), nil
}
