package injector

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

var testSecrets = map[string]string{
	"ALPHA_KEY": "value-a",
	"BETA_KEY":  "value-b",
}

// --- Get ---

func TestGetValidFormats(t *testing.T) {
	validFormats := []string{"shell", "sh", "bash", "zsh", "dotenv", "env", "jupyter", "notebook", "python"}
	for _, f := range validFormats {
		inj, err := Get(f)
		if err != nil {
			t.Errorf("Get(%q) returned error: %v", f, err)
		}
		if inj == nil {
			t.Errorf("Get(%q) returned nil", f)
		}
	}
}

func TestGetUnknownFormat(t *testing.T) {
	_, err := Get("xml")
	if err == nil {
		t.Error("Get(xml) should return error")
	}
}

// --- Shell injector ---

func TestShellInjector(t *testing.T) {
	inj, _ := Get("shell")
	out, err := inj.Inject(testSecrets)
	if err != nil {
		t.Fatalf("shell inject failed: %v", err)
	}

	if !strings.Contains(out, "export ALPHA_KEY='value-a'") {
		t.Error("shell output missing ALPHA_KEY export")
	}
	if !strings.Contains(out, "export BETA_KEY='value-b'") {
		t.Error("shell output missing BETA_KEY export")
	}
}

func TestShellInjectorSorted(t *testing.T) {
	inj, _ := Get("shell")
	out, _ := inj.Inject(testSecrets)

	lines := strings.Split(strings.TrimSpace(out), "\n")
	if len(lines) != 2 {
		t.Fatalf("expected 2 lines, got %d", len(lines))
	}
	// ALPHA before BETA
	if !strings.HasPrefix(lines[0], "export ALPHA_KEY") {
		t.Errorf("first line should be ALPHA_KEY, got: %s", lines[0])
	}
}

func TestShellInjectorEscapesSingleQuotes(t *testing.T) {
	secrets := map[string]string{
		"KEY": "it's a test",
	}
	inj, _ := Get("shell")
	out, _ := inj.Inject(secrets)

	// Single quotes in values should be escaped as: '\''
	if !strings.Contains(out, `'it'\''s a test'`) {
		t.Errorf("single quotes not escaped correctly: %s", out)
	}
}

func TestShellInjectorEmpty(t *testing.T) {
	inj, _ := Get("shell")
	out, err := inj.Inject(map[string]string{})
	if err != nil {
		t.Fatalf("shell inject with empty map failed: %v", err)
	}
	if out != "" {
		t.Errorf("empty secrets should produce empty output, got: %q", out)
	}
}

// --- Dotenv injector ---

func TestDotenvInjector(t *testing.T) {
	inj, _ := Get("dotenv")
	out, err := inj.Inject(testSecrets)
	if err != nil {
		t.Fatalf("dotenv inject failed: %v", err)
	}

	if !strings.Contains(out, "ALPHA_KEY=value-a") {
		t.Error("dotenv output missing ALPHA_KEY")
	}
	if !strings.Contains(out, "# Generated by aikeys") {
		t.Error("dotenv output missing header comment")
	}
}

func TestDotenvInjectorQuotesSpecialChars(t *testing.T) {
	secrets := map[string]string{
		"KEY": "value with spaces",
	}
	inj, _ := Get("dotenv")
	out, _ := inj.Inject(secrets)

	if !strings.Contains(out, `KEY="value with spaces"`) {
		t.Errorf("dotenv should quote values with spaces: %s", out)
	}
}

func TestDotenvInjectorNoQuotesSimpleValues(t *testing.T) {
	secrets := map[string]string{
		"KEY": "simplevalue",
	}
	inj, _ := Get("dotenv")
	out, _ := inj.Inject(secrets)

	if strings.Contains(out, `"simplevalue"`) {
		t.Errorf("dotenv should not quote simple values: %s", out)
	}
}

func TestDotenvInjectorEscapesDoubleQuotesInValues(t *testing.T) {
	secrets := map[string]string{
		"KEY": `value with "quotes" inside`,
	}
	inj, _ := Get("dotenv")
	out, _ := inj.Inject(secrets)

	if !strings.Contains(out, `\"quotes\"`) {
		t.Errorf("dotenv should escape double quotes: %s", out)
	}
}

// --- Jupyter injector ---

func TestJupyterInjector(t *testing.T) {
	inj, _ := Get("jupyter")
	out, err := inj.Inject(testSecrets)
	if err != nil {
		t.Fatalf("jupyter inject failed: %v", err)
	}

	if !strings.HasPrefix(out, "import os\n") {
		t.Error("jupyter output should start with 'import os'")
	}
	if !strings.Contains(out, "os.environ['ALPHA_KEY'] = 'value-a'") {
		t.Error("jupyter output missing ALPHA_KEY assignment")
	}
}

func TestJupyterInjectorEscapesBackslashes(t *testing.T) {
	secrets := map[string]string{
		"KEY": `path\to\file`,
	}
	inj, _ := Get("jupyter")
	out, _ := inj.Inject(secrets)

	if !strings.Contains(out, `path\\to\\file`) {
		t.Errorf("jupyter should escape backslashes: %s", out)
	}
}

func TestJupyterInjectorEscapesSingleQuotes(t *testing.T) {
	secrets := map[string]string{
		"KEY": "it's a value",
	}
	inj, _ := Get("jupyter")
	out, _ := inj.Inject(secrets)

	if !strings.Contains(out, `it\'s a value`) {
		t.Errorf("jupyter should escape single quotes: %s", out)
	}
}

// --- WriteToFile ---

func TestWriteToFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "output.env")

	err := WriteToFile(path, "KEY=value\n")
	if err != nil {
		t.Fatalf("WriteToFile failed: %v", err)
	}

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("could not read written file: %v", err)
	}
	if string(data) != "KEY=value\n" {
		t.Errorf("file content = %q, want %q", string(data), "KEY=value\n")
	}

	info, _ := os.Stat(path)
	if info.Mode().Perm() != 0600 {
		t.Errorf("file permissions = %o, want 0600", info.Mode().Perm())
	}
}

// --- sortedKeys ---

func TestSortedKeys(t *testing.T) {
	m := map[string]string{"C": "3", "A": "1", "B": "2"}
	keys := sortedKeys(m)

	if len(keys) != 3 {
		t.Fatalf("sortedKeys returned %d keys, want 3", len(keys))
	}
	if keys[0] != "A" || keys[1] != "B" || keys[2] != "C" {
		t.Errorf("sortedKeys = %v, want [A B C]", keys)
	}
}
