package e2e

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// --- Shell format ---

func TestInjectShell(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"API_KEY":    "secret-value",
		"OTHER_KEY":  "other-value",
	})

	stdout, _, err := llmvlt(t, storePath, "inject")
	if err != nil {
		t.Fatalf("inject failed: %v", err)
	}
	assertContains(t, stdout, "export API_KEY=", "shell output")
	assertContains(t, stdout, "export OTHER_KEY=", "shell output")
	assertContains(t, stdout, "secret-value", "shell output")
}

func TestInjectShellExplicitFormat(t *testing.T) {
	storePath := createVault(t, map[string]string{"KEY": "val"})

	for _, format := range []string{"shell", "sh", "bash", "zsh"} {
		stdout, _, err := llmvlt(t, storePath, "inject", "--format", format)
		if err != nil {
			t.Errorf("inject --format %s failed: %v", format, err)
			continue
		}
		assertContains(t, stdout, "export KEY=", format+" output")
	}
}

func TestInjectShellEscapesSingleQuotes(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"KEY": "it's a test",
	})

	stdout, _, err := llmvlt(t, storePath, "inject", "--format", "shell")
	if err != nil {
		t.Fatalf("inject failed: %v", err)
	}
	// Single quotes should be escaped for safe shell eval
	assertContains(t, stdout, `'\''`, "shell escape")
}

// --- Dotenv format ---

func TestInjectDotenv(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"API_KEY":   "secret-value",
		"OTHER_KEY": "other-value",
	})

	stdout, _, err := llmvlt(t, storePath, "inject", "--format", "dotenv")
	if err != nil {
		t.Fatalf("inject dotenv failed: %v", err)
	}
	assertContains(t, stdout, "API_KEY=secret-value", "dotenv output")
	assertContains(t, stdout, "OTHER_KEY=other-value", "dotenv output")
	assertContains(t, stdout, "# Generated by llmvlt", "dotenv header")
}

func TestInjectDotenvEnvAlias(t *testing.T) {
	storePath := createVault(t, map[string]string{"KEY": "val"})

	stdout, _, err := llmvlt(t, storePath, "inject", "--format", "env")
	if err != nil {
		t.Fatalf("inject --format env failed: %v", err)
	}
	assertContains(t, stdout, "KEY=val", "env output")
}

func TestInjectDotenvQuotesSpaces(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"KEY": "value with spaces",
	})

	stdout, _, err := llmvlt(t, storePath, "inject", "--format", "dotenv")
	if err != nil {
		t.Fatalf("inject failed: %v", err)
	}
	assertContains(t, stdout, `"value with spaces"`, "dotenv quoted")
}

// --- Jupyter format ---

func TestInjectJupyter(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"API_KEY": "secret-value",
	})

	stdout, _, err := llmvlt(t, storePath, "inject", "--format", "jupyter")
	if err != nil {
		t.Fatalf("inject jupyter failed: %v", err)
	}
	assertContains(t, stdout, "import os", "jupyter import")
	assertContains(t, stdout, "os.environ['API_KEY'] = 'secret-value'", "jupyter output")
}

func TestInjectJupyterAliases(t *testing.T) {
	storePath := createVault(t, map[string]string{"KEY": "val"})

	for _, format := range []string{"jupyter", "notebook", "python"} {
		stdout, _, err := llmvlt(t, storePath, "inject", "--format", format)
		if err != nil {
			t.Errorf("inject --format %s failed: %v", format, err)
			continue
		}
		assertContains(t, stdout, "import os", format+" output")
	}
}

func TestInjectJupyterEscapesBackslashes(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"KEY": `path\to\file`,
	})

	stdout, _, err := llmvlt(t, storePath, "inject", "--format", "jupyter")
	if err != nil {
		t.Fatalf("inject failed: %v", err)
	}
	assertContains(t, stdout, `path\\to\\file`, "jupyter backslash escape")
}

// --- Unknown format ---

func TestInjectUnknownFormat(t *testing.T) {
	storePath := createVault(t, map[string]string{"KEY": "val"})

	_, stderr, err := llmvlt(t, storePath, "inject", "--format", "xml")
	if err == nil {
		t.Fatal("expected error for unknown format")
	}
	assertContains(t, stderr, "unknown format", "stderr")
}

// --- Output to file ---

func TestInjectOutputToFile(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"KEY_A": "value-a",
		"KEY_B": "value-b",
	})

	outFile := filepath.Join(t.TempDir(), ".env")
	_, stderr, err := llmvlt(t, storePath,
		"inject", "--format", "dotenv", "-o", outFile)

	if err != nil {
		t.Fatalf("inject to file failed: %v\nstderr: %s", err, stderr)
	}
	assertContains(t, stderr, "Written to", "stderr")

	// Verify file contents
	data, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatalf("could not read output file: %v", err)
	}
	content := string(data)
	assertContains(t, content, "KEY_A=value-a", "file content")
	assertContains(t, content, "KEY_B=value-b", "file content")

	// Verify file permissions
	info, _ := os.Stat(outFile)
	if info.Mode().Perm() != 0600 {
		t.Errorf("output file permissions = %o, want 0600", info.Mode().Perm())
	}
}

// --- Empty vault ---

func TestInjectEmptyVault(t *testing.T) {
	storePath := createEmptyDir(t)
	llmvlt(t, storePath, "init")

	_, stderr, err := llmvlt(t, storePath, "inject")
	if err == nil {
		t.Fatal("expected error for empty vault inject")
	}
	assertContains(t, stderr, "no secrets", "stderr")
}

// --- Skips empty values ---

func TestInjectSkipsEmptyValues(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"FILLED":     "has-value",
		"SCAFFOLDED": "",
	})

	stdout, _, err := llmvlt(t, storePath, "inject", "--format", "dotenv")
	if err != nil {
		t.Fatalf("inject failed: %v", err)
	}
	assertContains(t, stdout, "FILLED=has-value", "dotenv output")
	assertNotContains(t, stdout, "SCAFFOLDED", "dotenv output")
}

// --- Output is sorted ---

func TestInjectOutputIsSorted(t *testing.T) {
	storePath := createVault(t, map[string]string{
		"ZEBRA": "z",
		"ALPHA": "a",
		"MIDDLE": "m",
	})

	stdout, _, err := llmvlt(t, storePath, "inject", "--format", "shell")
	if err != nil {
		t.Fatalf("inject failed: %v", err)
	}

	lines := strings.Split(strings.TrimSpace(stdout), "\n")
	if len(lines) != 3 {
		t.Fatalf("expected 3 lines, got %d", len(lines))
	}
	if !strings.Contains(lines[0], "ALPHA") {
		t.Errorf("first line should contain ALPHA, got: %s", lines[0])
	}
	if !strings.Contains(lines[2], "ZEBRA") {
		t.Errorf("last line should contain ZEBRA, got: %s", lines[2])
	}
}

func TestInjectWrongPassword(t *testing.T) {
	storePath := createVault(t, map[string]string{"KEY": "val"})
	_, stderr, err := llmvltWithPassword(t, storePath, "wrong", "inject")
	if err == nil {
		t.Fatal("expected error with wrong password")
	}
	assertContains(t, stderr, "wrong password", "stderr")
}
